kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.24.14
imageRepository: registry.k8s.io
controllerManager:
  extraArgs:
    leader-elect: "false"
    profiling: "false"
scheduler:
  extraArgs:
    leader-elect: "false"
    profiling: "false"
dns:
  imageRepository: registry.k8s.io
  imageTag: v1.9.3
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    imageRepository: registry.k8s.io
    imageTag: v3.5.6
networking:
  podSubnet: "10.244.0.0/16"
apiServer:
  extraArgs:
    profiling: "false"
  certSANs:
    - 34.66.72.135
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
imageGCHighThresholdPercent: 100
imageGCLowThresholdPercent: 99
evictionHard:
  "imagefs.available": "0%"
